services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=changeme
    networks:
      - predictice-bridge-network

  application:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
    environment:
      SPRING_DATA_ELASTICSEARCH_HOST: elasticsearch
    restart: on-failure
    networks:
      - predictice-bridge-network

networks:
  predictice-bridge-network:
    driver: bridge
