openapi: 3.0.3

info:
  title: Predictice Music Library API description
  version: 0.0.1-SNAPSHOT

paths:
  /albums/search:
    get:
      operationId: searchAlbums
      summary: Search for albums
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: year
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlbumsSearchResult'
        500:
          description: Unexpected error

components:
  schemas:

    AlbumsSearchResult:
      type: object
      properties:
        resultCount:
          type: integer
          description: Total number of search results
        releaseYears:
          type: array
          description: All existing release years for the searched albums
          items:
            $ref: '#/components/schemas/ReleaseYearResource'
        albums:
          type: array
          description: Found albums based on the search query
          items:
            $ref: '#/components/schemas/AlbumResource'

    ReleaseYearResource:
      type: object
      properties:
        year:
          type: string
          description: Album release year
        albumCount:
          type: integer
          description: Number of albums released for this year

    AlbumResource:
      type: object
      properties:
        id:
          type: string
          description: Album UUID
        title:
          type: string
          description: Album title
        artist:
          type: string
          description: Album artist
        releaseYear:
          type: string
          description: Album release year
        coverUrl:
          type: string
          description: Album cover URL
